<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?= $title?></title>
        <style>
            .alert-box {
                padding: 20px;
                margin-bottom: 20px;
                border: 1px solid transparent;
                border-radius: 4px; 
                color: #a94442;
                background-color: #f2dede;
                border-color: #ebccd1;
                font-family: Arial, Helvetica, sans-serif;
            }

            .success-box {
                padding: 20px;
                margin-bottom: 20px;
                border: 1px solid transparent;
                border-radius: 4px; 
                color: #5fc240;
                background-color: #def2de;
                border-color: #d1ebcc;
                font-family: Arial, Helvetica, sans-serif;
            }

            div.profile img{
                width: 100px;
            }
            div.profile {
                font-family: Verdana, Arial, Helvetica, sans-serif;
            }
            form.modify-info {
                font-family: Verdana, Arial, Helvetica, sans-serif;
            }

            .photo{
                width: 45%;
                margin:5px
            }

            div.takepic {
                position: relative;
            }

            div.camera {
                position: absolute;
                top: 0px;
                z-index: 15;
            }
            div.cap {
                position: absolute;
                top: 0px;
            }
            div.sitcker{
                position: absolute;
                top: 800px;
            }
            div.sitcker img{
                width: 100px;
            }

            div.camera video{
                z-index: 5;
                position: absolute;
                top: 0px;
                margin: 1em;
            }
            div.camera canvas {
                z-index: 15;
                position: absolute;
                top: 0px;
                margin: 1em;
            }
            div.camera button{
                z-index: 15;
                position: absolute;
                top: 500px;
                left: 520px;
                border-radius: 3px; 
                cursor: pointer; 
                display: inline-block; 
                font-family: Verdana, sans-serif; 
                font-weight: 800;
                font-size: 12px; 
                font-weight: 400; 
                line-height: 20px; 
                padding: 9px 16px 9px;
                margin: 16px 0 0 16px; 

            }
            div.sticker {
                position: absolute;
                top: 0px;
            }

            div.uploadpic {
                position: absolute;
                margin: 1em;
                top: 0px;
                left: 700px;
            }

            div.uploadpic button{
                z-index: 15;
                position: absolute;
                top: 500px;
                left: 520px;
                border-radius: 3px; 
                cursor: pointer; 
                display: inline-block; 
                font-family: Verdana, sans-serif; 
                font-weight: 800;
                font-size: 12px; 
                font-weight: 400; 
                line-height: 20px; 
                padding: 9px 16px 9px;
                margin: 16px 0 0 16px; 
            }

            div.single_photo{
                position: relative;
            }

            .comment input{
                width: 200px;
                margin: 10px;
            }
            
            #like_photo{
                cursor: pointer; 
            }

/* 
            footer{
                position: absolute;
                top: calc(95%);
            } */

        </style>
    </head>
    <body>
        <?= $content ?>
        <!-- <footer><h5>© 2019 Cchi Camagrue</h5></footer> -->
    </body>
</html>