<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?= $title?></title>
        <!-- <link rel="stylesheet" href = "stylesheet.css" type = "text/css" /> -->
        <style>
            body{
    background-color: #ebe6cc;
}
.alert-box {
    padding: 20px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    border-radius: 4px; 
    color: #a94442;
    background-color: #f2dede;
    border-color: #ebccd1;
    font-family: Arial, Helvetica, sans-serif;
}
.success-box {
    padding: 20px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    border-radius: 4px; 
    color: #5fc240;
    background-color: #def2de;
    border-color: #d1ebcc;
    font-family: Arial, Helvetica, sans-serif;
}

.login-box form{
    left: calc(100% - 100px);
}

.login-box input{
    border-radius: 3em;
    padding: 0.7em;
    margin: 5px;
    border: 0;
    outline: 0;
    background-color: #acb8be;
    color: #e7e5e0;
    text-transform: uppercase;
    cursor: pointer;
}

.modify-info input{
    padding: 0.3em;
    margin: 5px;
    border: 0;
    outline: 0;
    background-color: white;
    color: black;
    cursor: text;
    width: 140px;
}
.modify-info input[type=button]{
    background-color: #d7dde0;
    color: white;
}
.modify-info input[type=button]:hover{
    background-color: #a06d7c;
    cursor: pointer;
}

#log-bx-input{
    background-color: white;
    cursor: text;
    color: #a59d8a;
    text-transform: none;
}

#login-box-btn {
    padding: 0.5em;
    font-size: 12px;
    border: 0;
    outline: 0;
    border-radius: 5em;
    box-sizing: border-box;
    color: #e7e5e0;
    position: absolute;
    left: 157px;
    top: 25px;
}

#err-rel{
    padding: 1em;
    font-size: 12px;
    border: 0;
    outline: 0;
    border-radius: 2em;
    box-sizing: border-box;
    color: #3f4d52;
    width: 100px; 
}

#err-rel:hover{
    background-color: #f0e6b4;
    cursor: pointer;
    border: 2px solid white;
}

#logout[type=submit]{
    border-radius: 3em;
    padding: 0.7em;
    margin: 5px;
    border: 0;
    outline: 0;
    background-color: #acb8be;
    color: #e7e5e0;
    text-transform: uppercase;
    cursor: pointer;
}
#logout[type=submit]:hover{
    background-color: #a06d7c;
    /* border: 2px solid #e5d8db; */
}
#login-link[type=button]{
    border-radius: 3em;
    padding: 0.7em;
    margin: 5px;
    border: 0;
    outline: 0;
    background-color: #acb8be;
    color: #e7e5e0;
    cursor: pointer;
}
#login-link[type=button]:hover{
    background-color: #81939c;
}
div.profile img{
    width: 100px;
}
div.profile {
    font-family: Verdana, Arial, Helvetica, sans-serif;
}
form.modify-info {
    font-family: Verdana, Arial, Helvetica, sans-serif;
}

.photo{
    width: 45%;
    margin:5px
    
}

.mygallery{
    display: flex;
    flex-wrap: wrap;
}
.mygallery > div{
    width: 400px;
    margin: 10px;
}
.myphoto{
    width: 90%;
}

div.takepic {
    position: relative;
}

div.camera {
    position: absolute;
    top: 0px;
    z-index: 15;
}

div.sitcker{
    position: absolute;
    top: 800px;
}
div.sitcker img{
    width: 100px;
}

div.camera video{
    position: absolute;
    top: 0px;
    margin: 1em;
}
div.camera #canvas2 {
    position: absolute;
    top: 0px;
    margin: 1em;
}
div.camera #canvas1 {
    position: absolute;
    top: 0px;
    margin: 1em;
}

div.camera div{
    position: absolute;
    top: 500px;
    margin: 2em;
}
#clearcnv {
    z-index: 15;
    position: absolute;
    top: 500px;
    left: 300px;
    border-radius: 3px; 
    cursor: pointer; 
    display: inline-block; 
    font-family: Verdana, sans-serif; 
    font-weight: 800;
    font-size: 12px; 
    font-weight: 400; 
    line-height: 20px; 
    padding: 9px 16px 9px;
    margin: 16px 0 0 16px; 
}
#capture-btn{
    z-index: 15;
    position: absolute;
    top: 500px;
    left: 520px;
    border-radius: 3px; 
    cursor: pointer; 
    display: inline-block; 
    font-family: Verdana, sans-serif; 
    font-weight: 800;
    font-size: 12px; 
    font-weight: 400; 
    line-height: 20px; 
    padding: 9px 16px 9px;
    margin: 16px 0 0 16px; 
}

div.sticker {
    position: absolute;
    top: 0px;
}

div.uploadpic {
    position: absolute;
    margin: 1em;
    top: 0px;
    left: 700px;
}

div.uploadpic button{
    z-index: 15;
    position: absolute;
    top: 500px;
    left: 520px;
    border-radius: 3px; 
    cursor: pointer; 
    display: inline-block; 
    font-family: Verdana, sans-serif; 
    font-weight: 800;
    font-size: 12px; 
    font-weight: 400; 
    line-height: 20px; 
    padding: 9px 16px 9px;
    margin: 16px 0 0 16px; 
}

div.upl-img{
    font-family: Verdana, sans-serif;
    font-size: 10px; 
}

div.single_photo{
    position: relative;
}

.cmmtctx {
    font-family: 'Palatino Linotype', 'Book Antiqua', Palatino, serif;
    font-size: 15px; 
}
.cmmtctx h5{
    font-family: 'Palatino Linotype', 'Book Antiqua', Palatino, serif;
    font-size: 12px;
    
}
.comment input{
    width: 200px;
    margin: 10px;
}

#like_photo{
    cursor: pointer; 
}

.lnk-page {
    margin: 10px;
    padding: 10px;
}
.lnk-page > a{
    color: #666;
    font-family: Arial, sans-serif; 
    border: 2px solid;
    border-radius: 50%;
    font-size: 14px;
    width: 30px;
    height: 30px;
    padding: 8px;
    text-decoration: none;
}

        </style>
    </head>
    <body>
        <?= $content ?>
        <!-- <footer><h5>© 2019 Cchi Camagrue</h5></footer> -->
    </body>
</html>