<div class='allgallery'>
<?php
    $p = 0;
    if (isset($_GET['page'])){
        $p = intval($_GET['page']) * 6;
    }
    for ($i = 0; $i < 6; $i++) {
        $j = $i + $p;
        if (isset($rsltAllgallery[$j])){
            $fname = $rsltAllgallery[$j]['filename'];
            if (isset($fname)){
                echo "<a href='/gallery/p?pic=".$fname."&id_photo=".$rsltAllgallery[$j]['id_photo']."'>
                <img class='photo' name='.$fname.' src='/uploads/photo/".$fname."'></a>";
            }
        }
    }
?>
</div>
<br/>
<br/>
<div class="lnk-page">
<?php
    $t = 0;
    foreach($rsltAllgallery as $value){
        $t++;
    }
    $pages = $t / 6;
    for($t=0; $t < $pages; $t++)
        echo "<a href='gallery?page=".$t."'>".$t."</a>";
?>
</div>