<form class='comment' method='post' name='comment' action="#">
        <input type="text" name="uid" placeholder="Username" value="<?php if (isset($_SESSION['user'])){echo $_SESSION['user'];}?>" required/><br/>
        <input type="text" name="comment" placeholder="leave your comment..." style="height: 60px;"required/><br/>
        <input id="snd-cmt-btn" type="submit" value="Send" style="width: 50px;"> 
</form>