<?php
if (isset($_GET['error'])){
        if ($_GET['error'] == "invaliduid"){ 
                echo "<div class=\"alert-box\">Invalid Username, Please contain only characters and numbers.</div>"; 
        }else if($_GET['error'] == "emptyfields"){
                echo "<div class=\"alert-box\">Empty fields.</div>"; 
        }else if($_GET['error'] == "invalidemail"){
                echo "<div class=\"alert-box\">Invalid E-mail address.</div>"; 
        }else if ($_GET['error'] == "invalidpwd"){
                echo '<div class="alert-box">Password should be at least 8 characters, include 1 upper case letter, 1 number, 1 special character !@#$%.</div>';
        }else if ($_GET['error'] == "usrnmexist"){
                echo '<div class=\"alert-box\">Username exist.</div>';
        }else if ($_GET['error'] == "emailexist"){
                echo '<div class=\"alert-box\">E-mail exist.</div>';
        }else if ($_GET['error'] == "sql"){
                echo '<div class=\"alert-box\">Problem of Create NewUser, please try later.</div>';
        }
}
?>