<div class=login-box>
    <form action="index" method="post">
        <h1>Login</h1>
        <input id="tx" type="text" name="login" placeholder="Username">
        <br />
        <input id="tx" type="password" name="passwd" placeholder="password">
        <br />
        <input type="submit" name="submit" value="Login">
    </form>
    <a href="newuser"><input type="button" value="Sign Up"></a>
</div>