<?php include "Views/displayError.phtml"?>
<div class=login-box>
    <form method="post">
        <h2>Login</h2>
        <input type="text" name="uid" placeholder="Username" value="<?php if (isset($_GET['uid'])) {echo $_GET['uid'];}?>" required>
        <br />
        <input type="password" name="passwd" placeholder="password" required>
        <br />
        <input type="submit" value="login">
    </form>
    <a href="/newuser"><input type="button" value="Sign Up"></a>
    <a href="/login/forgot_password"><input type="button" value="Forgot password"></a>
</div>