<a href="/profile"><input id="login-link" type="button" value="To my Profile Page"></a>
<a href="/gallery/take_photo"><input id="login-link" type="button" value="Take A Photo"></a>
<a href="/gallery/my_gallery"><input id="login-link" type="button" value="My Gallery"></a>
<a href="/gallery"><input id="login-link" type="button" value="To Gallery"></a>
<form method="POST"><input id="logout" type="submit" name="submit" value="Logout"></form>