<?php include "Views/displayError.phtml"?>
<form method="post">
        <h2>Sign Up</h2>
        <input type="text" name="uid" placeholder="Username" value=<?php if(isset($_GET['uid'])){return $_GET['uid'];}?>>
        <br />
        <input type="password" name="pwd"  placeholder="password">
        <br />
        <input type="password" name="pwd-repeat" placeholder="Repeat Password">
        <br />
        <input type="text" name="email" placeholder="E-mail" value=<?php if(isset($_GET['email'])){return $_GET['email'];}?>>
        <br />
        <input type="submit" name="submit" value="SignUp">
</form>
<h5>Already Member?<h5>
<a href="index"><input type="button" value="Return to LoginPage"></a>