<div class="profile">
    Hello <?= $_SESSION['user']?><br/>
    <img src='/uploads/<?php echo $this->pic_pro;?>' ><br/>
    UID:   <?php echo $_SESSION['user']?><br/>
    Email: <?php echo $this->email;?><br/>
    Email Verify: <?php echo $this->confirmed;?><br/>
</div>
<p><?= $profilemodel->profileInfo['email']?></p>
<a href="/profile/modify"><input type="button" value="Modify Info"></a>
<a href="/gallery"><input type="button" value="Gallery"></a>