<?php
    if (isset($_GET['verify'])){
        echo "<div class='alert-box'>You have to verify your email first to start to use Camagru.</div>";
    }
?>
<div class="profile">
    <li>Hello <?= $_SESSION['user']?></li>
    <li>UID:   <?php echo $_SESSION['user']?></li>
    <li>Email: <?php echo $this->email;?></li>
    <li>Email Verify: <?php echo $this->confirmed;?></li>
    <a href="/profile/modify"><input  id='login-link' class='modify-info' type="button" value="Modify Info"></a>
</div>