<video id="player" width="640" height="480" autoplay></video>
<button id="capture-btn">Capture</button>
<form enctype="multipart/form-data" class="uploadform">
    <canvas id="canvas" name="canvas" width="640px" height="480px"></canvas>
    <!-- <canvas id="canvas2" wirdth="640px" height="480px"></canvas> -->
    <button id="upload-btn" name="uploadphoto">upload</button>
</form>
<script src="/js/camera.js"></script>