<div class='takepic'>
    <div class='camera'>
        <video id="player" width="640" height="480" autoplay></video>
        <canvas id="canvas2" width="640px" height="480px"></canvas>
        <button id="clearcnv">Clear</button>
        <button id="capture-btn">Capture</button>
    </div>
    <div class='sitcker'>
        <?php foreach ($stickers as $value){
                echo "<img id='".$value['id_sticker']."' name='".$value['sticker_name']."' src='/uploads/sticker/".$value['sticker_name']."'>";
            }?>
    </div>
    <div class='uploadpic'>
        <form enctype="multipart/form-data" class="uploadform">
            <canvas id="canvas" name="canvas" width="640px" height="480px"></canvas>
            <button id="upload-btn" name="uploadphoto">upload</button>
        </form>
    </div>
</div>
<script src="/js/camera.js"></script>
